--------------------------------------------------------
--  File created - Tuesday-November-14-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_STD_GRADES
--------------------------------------------------------

  CREATE TABLE "DPSPROJECT"."T_STD_GRADES" 
   (	"STDNO" NUMBER(9,0), 
	"CCYRCD" NUMBER(4,0), 
	"SEMCD" NUMBER(2,0), 
	"L_ABR_CRSNO" VARCHAR2(8 BYTE), 
	"CRSNO" NUMBER(8,0), 
	"SECTNO" NUMBER(3,0), 
	"GRADECD_OLD" NUMBER(2,0), 
	"GRADECD_NEW" NUMBER(2,0), 
	"INCOMPLETE_NOTIFICATION" VARCHAR2(1 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USERNAME" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USERNAME" VARCHAR2(20 BYTE), 
	"COMMENTS" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STD_GRADES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DPSPROJECT"."STD_GRADES_PK" ON "DPSPROJECT"."T_STD_GRADES" ("STDNO", "CCYRCD", "SEMCD", "L_ABR_CRSNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table T_STD_GRADES
--------------------------------------------------------

  ALTER TABLE "DPSPROJECT"."T_STD_GRADES" ADD CONSTRAINT "STD_GRADES_PK" PRIMARY KEY ("STDNO", "CCYRCD", "SEMCD", "L_ABR_CRSNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DPSPROJECT"."T_STD_GRADES" MODIFY ("STDNO" NOT NULL ENABLE);
 
  ALTER TABLE "DPSPROJECT"."T_STD_GRADES" MODIFY ("CCYRCD" NOT NULL ENABLE);
 
  ALTER TABLE "DPSPROJECT"."T_STD_GRADES" MODIFY ("SEMCD" NOT NULL ENABLE);
 
  ALTER TABLE "DPSPROJECT"."T_STD_GRADES" MODIFY ("L_ABR_CRSNO" NOT NULL ENABLE);
 
  ALTER TABLE "DPSPROJECT"."T_STD_GRADES" MODIFY ("CRSNO" NOT NULL ENABLE);
 
  ALTER TABLE "DPSPROJECT"."T_STD_GRADES" MODIFY ("GRADECD_OLD" NOT NULL ENABLE);
 
  ALTER TABLE "DPSPROJECT"."T_STD_GRADES" MODIFY ("GRADECD_NEW" NOT NULL ENABLE);
 
  ALTER TABLE "DPSPROJECT"."T_STD_GRADES" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "DPSPROJECT"."T_STD_GRADES" MODIFY ("CREATE_USERNAME" NOT NULL ENABLE);
