--------------------------------------------------------
--  File created - Monday-May-22-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_REG_DROPW
--------------------------------------------------------

  CREATE TABLE "DPSPROJECT"."T_REG_DROPW" 
   (	"STDNO" NUMBER(9,0), 
	"STDSTATCD" NUMBER(9,0), 
	"CRSNO" NUMBER(8,0), 
	"SECTCD" NUMBER(8,0), 
	"SECTNO" NUMBER(3,0), 
	"STATUSCD" NUMBER(4,0), 
	"CREATE_DATE" DATE, 
	"CREATE_USERNAME" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USERNAME" VARCHAR2(20 BYTE), 
	"COMMENTS" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_REG_DROPW_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DPSPROJECT"."T_REG_DROPW_PK" ON "DPSPROJECT"."T_REG_DROPW" ("STDNO", "STDSTATCD", "CRSNO", "SECTCD", "SECTNO", "STATUSCD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table T_REG_DROPW
--------------------------------------------------------

  ALTER TABLE "DPSPROJECT"."T_REG_DROPW" MODIFY ("STDNO" NOT NULL ENABLE);
 
  ALTER TABLE "DPSPROJECT"."T_REG_DROPW" MODIFY ("CRSNO" NOT NULL ENABLE);
 
  ALTER TABLE "DPSPROJECT"."T_REG_DROPW" MODIFY ("SECTCD" NOT NULL ENABLE);
 
  ALTER TABLE "DPSPROJECT"."T_REG_DROPW" MODIFY ("SECTNO" NOT NULL ENABLE);
 
  ALTER TABLE "DPSPROJECT"."T_REG_DROPW" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "DPSPROJECT"."T_REG_DROPW" MODIFY ("CREATE_USERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "DPSPROJECT"."T_REG_DROPW" MODIFY ("STDSTATCD" NOT NULL ENABLE);
 
  ALTER TABLE "DPSPROJECT"."T_REG_DROPW" MODIFY ("STATUSCD" NOT NULL ENABLE);
 
  ALTER TABLE "DPSPROJECT"."T_REG_DROPW" ADD CONSTRAINT "T_REG_DROPW_PK" PRIMARY KEY ("STDNO", "STDSTATCD", "CRSNO", "SECTCD", "SECTNO", "STATUSCD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
